version: "3.7"
services:

  product:
    build:
      context: .
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      MONGO_HOST: mongo

  mongo:
    image: mongo:3.6.17-xenial
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: user
