version: "3.7"
services:

  product:
    image: myretail/product
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      REDSKY_BASE_URL: http://mockserver:1080

  mongo:
    image: mongo:3.6.17-xenial
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: user

  mockserver:
    image: mockserver/mockserver:mockserver-5.11.1
    environment:
      MOCKSERVER_LIVENESS_HTTP_GET_PATH: /health
