spring:
  data:
    mongodb:
      authentication-database: ${MONGO_AUTH_DB:admin}
      username: ${MONGO_USER:root}
      password: ${MONGO_PASSWORD:password}
      database: ${MONGO_PRICE_DB:price}
      host: ${MONGO_HOST:mongo}
      port: ${MONGO_PORT:27017}
